# Generated by Django 5.2.1 on 2025-05-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('total_experience', models.IntegerField()),
                ('availability', models.CharField(max_length=50)),
                ('preferred_job', models.CharField(max_length=50)),
                ('qualification_data', models.JSONField()),
                ('company_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('role_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('skills', models.CharField(max_length=500)),
            ],
        ),
    ]
