# Generated by Django 5.2.1 on 2025-05-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='first_name',
            new_name='fName',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='last_name',
            new_name='lName',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='preferred_job',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='qualification_data',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='role_description',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='total_experience',
        ),
    ]
