# Generated by Django 5.2.1 on 2025-05-16 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cv_addr_cv_availability_cv_bachelors_obtained_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='bachelors_obtained_marks',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='bachelors_total_marks',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='inter_obtained_marks',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='inter_total_marks',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='masters_obtained_marks',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='masters_total_marks',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='matric_obtained_marks',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='matric_total_marks',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='start_date',
        ),
    ]
