# Generated by Django 5.2.1 on 2025-05-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cv_bachelors_obtained_marks_cv_bachelors_total_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='end_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='start_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
