# Generated by Django 5.2.1 on 2025-05-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cv_end_date_alter_cv_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='bachelors_grade',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
