# Generated by Django 5.2.1 on 2025-05-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cv_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='studentOrNot',
            field=models.CharField(blank=True, null=True),
        ),
    ]
